[package]
name = "bend-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.1"
getopts = "0.2"
rayon = "1.5.1"
indicatif = "0.16.2"